version: '3.3'

services:
  bot:
    image: bot-image
    container_name: bot
    stop_signal: SIGINT
    build:
      context: .
    working_dir: "/usr/src/app/bot"
    volumes:
    - .:/usr/src/app/bot
    command: python3 -m bot
    restart: always
    env_file:
      - ".env"
    networks:
    - tg_bot

  nginx:
    image: nginx:1.21.6
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./log:/var/log/nginx
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80

networks:
  tg_bot:
    driver: bridge
