# Generated by Django 4.1.1 on 2022-09-26 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supportrequest',
            old_name='time',
            new_name='created_time',
        ),
        migrations.RemoveField(
            model_name='supportrequest',
            name='message',
        ),
    ]
